# Generated by Django 5.2.8 on 2026-07-01 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='courier_logos')),
                ('api_base_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_delivery_days', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('success_rate', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('rto_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_own_fleet', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aggregator_courier_partner',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CourierRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('METRO', 'Metro'), ('NATIONAL', 'National'), ('SPECIAL', 'Special')], max_length=20)),
                ('min_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additional_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='aggregator.courierpartner')),
            ],
            options={
                'db_table': 'aggregator_rate_card',
            },
        ),
        migrations.CreateModel(
            name='CourierServiceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_pincode', models.CharField(max_length=10)),
                ('destination_pincode', models.CharField(max_length=10)),
                ('estimated_days', models.IntegerField(default=3)),
                ('is_cod_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceability', to='aggregator.courierpartner')),
            ],
            options={
                'db_table': 'aggregator_serviceability',
                'indexes': [models.Index(fields=['origin_pincode', 'destination_pincode'], name='aggregator__origin__62429c_idx')],
                'unique_together': {('courier', 'origin_pincode', 'destination_pincode')},
            },
        ),
    ]
