# Generated by Django 5.2.8 on 2026-07-01 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregator', '0001_initial'),
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('pickup_contact_name', models.CharField(max_length=255)),
                ('pickup_contact_phone', models.CharField(max_length=15)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(blank=True, max_length=100)),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(blank=True, max_length=100)),
                ('delivery_pincode', models.CharField(max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('product_description', models.CharField(blank=True, max_length=500)),
                ('payment_mode', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash on Delivery')], default='PREPAID', max_length=10)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('READY_TO_SHIP', 'Ready to Ship'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERY_ATTEMPTED', 'Delivery Attempted'), ('DELIVERED', 'Delivered'), ('RTO_INITIATED', 'RTO Initiated'), ('RTO_IN_TRANSIT', 'RTO In Transit'), ('RETURNED', 'Returned'), ('FAILED', 'Failed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('LOST', 'Lost')], default='CREATED', max_length=30)),
                ('courier_awb', models.CharField(blank=True, max_length=50, null=True)),
                ('courier_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('courier_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregator.courierpartner')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='merchants.merchant')),
            ],
            options={
                'db_table': 'shipments_shipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shipments.shipment')),
            ],
            options={
                'db_table': 'shipments_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
